---
# Example interface configuration for this device
interfaces:
  - name: Loopback25
    description: "Test Demo - Configured by Ansible"
    enabled: true
    mtu: 1500
    ipv4_address: 192.0.2.33
    ipv4_prefix_length: 32